spring:
  application:
    name: app
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/reactstudy
    username: root
    password: 12345678
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
server:
  port: 8080
