spring:
  web:
    resources:
      static-locations: file:/media/
  application:
    name: app
  config:
    import: optional:file:./resources/.env
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always
  port: 8080

logging:
  level:
    org.hibernate: DEBUG
    org.springframework: DEBUG

jwt:
  secret-key: ${JWT_SECRET_KEY}